<?php

namespace App\Services;

use App\Models\Order;
use App\Models\Product;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class OrderService
{
    /**
     * Create an order from an already calculated payload.
     *
     * Used by the normal checkout flow.
     */
    public function create(array $data): Order
    {
        $data['order_number'] ??= 'ORD-' . strtoupper(Str::random(10));

        return Order::create($data);
    }

    /**
     * Create a manual order for Admin/Manager.
     *
     * Product prices, order totals, status and order number
     * are calculated/generated by the server.
     */
    public function createManualOrder(int $userId, array $items): Order
    {
        return DB::transaction(function () use ($userId, $items) {
            $totalAmount = 0;

            $order = Order::create([
                'order_number' => 'ORD-' . strtoupper(Str::random(10)),
                'user_id' => $userId,
                'total_amount' => 0,
                'status' => 'pending',
            ]);

            foreach ($items as $item) {
                $product = Product::findOrFail($item['product_id']);

                $quantity = (int) $item['quantity'];
                $unitPrice = (float) $product->price;
                $totalPrice = $unitPrice * $quantity;

                $order->items()->create([
                    'product_id' => $product->id,
                    'quantity' => $quantity,
                    'unit_price' => $unitPrice,
                    'total_price' => $totalPrice,
                ]);

                $totalAmount += $totalPrice;
            }

            $order->update([
                'total_amount' => $totalAmount,
            ]);

            return $order->load([
                'user',
                'items.product',
            ]);
        });
    }

    public function find(int $id): Order
    {
        return Order::with([
            'user',
            'items.product',
        ])->findOrFail($id);
    }

    public function all()
    {
        return Order::with([
            'user',
            'items.product',
        ])->latest()->get();
    }
}
