<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Daily Sales Report</title>
</head>

<body>

    <h2>Daily Sales Report</h2>

    <p>
        Date: <strong>{{ $date }}</strong>
    </p>

    <hr>

    <p>
        <strong>Total Orders:</strong>
        {{ $orders }}
    </p>

    <p>
        <strong>Paid Orders:</strong>
        {{ $paidOrders }}
    </p>

    <p>
        <strong>Total Revenue:</strong>
        ₹{{ number_format($revenue, 2) }}
    </p>

    <hr>

    <p>
        This is the daily sales report generated by the Enterprise Commerce system.
    </p>

</body>

</html>